import { Employee } from "@/types/general";

export const employeeData: Employee = {
    id: 1,
    employee_id: "EMP001",
    first_name: "John",
    last_name: "Doe",
    gender: "Male",
    user: { email: "johndoe@example.com" },
    id_card_photo: "https://via.placeholder.com/100",
    street: "123 Maple Street",
    state: "California",
    marital_status: "Single",
    department: "Human Resources",
    role: "HR Manager",
    salary: "$5000",
    resumption_date: "2023-01-15",
    referral_code: "REF1234",
    date_of_birth: "1990-05-20",
    phone: "555-123-4567",
    number_of_children: 0,
    number_of_dependent: 1,
    nationality: "American",
    state_of_origin: "California",
    lga_of_origin: "Los Angeles",
    account_name: "John Doe",
    account_number: "123456789",
    employee_medicals: [
      {
        id: 1,
        date_of_last_medical_checkup: "2023-06-15",
        hospital_conducted: "City Hospital",
        genotype: "AA",
        bloodgroup: "O+",
        document_name: "Medical_Report_2023.pdf",
        file: "https://example.com/medical_reports/Medical_Report_2023.pdf",
        reason_for_checkup: "Annual checkup",
      },
      {
        id: 2,
        date_of_last_medical_checkup: null,
        hospital_conducted: "Wellness Center",
        genotype: null,
        bloodgroup: "A-",
        document_name: null,
        file: null,
        reason_for_checkup: "Pre-employment screening",
      },
    ],
    employee_kins: [
      {
        id: 1,
        next_of_kin_fullname: "John Doe",
        relationship: "Brother",
        kin_address: "123 Main Street",
        email: "john.doe@example.com",
        phone: "1234567890",
        occupation: "Engineer",
        office_address: "Tech Corp, 456 Tech Avenue",
      },
      {
        id: 2,
        next_of_kin_fullname: "Jane Smith",
        relationship: "Mother",
        kin_address: null,
        email: null,
        phone: null,
        occupation: "Teacher",
        office_address: null,
      },
    ],
    employee_sanctions: [
      { id: 1, descriptions: "Late submission of project report" },
      { id: 2, descriptions: "Unauthorized leave" },
    ],
    employee_salary_advances: [
      { id: 1, salary_advance: 5000, salary_balance: 45000 },
      { id: 2, salary_advance: null, salary_balance: 50000 },
    ],
    employee_employment_histories: [
      {
        id: 1,
        name_of_company: "Tech Solutions",
        role: "Software Developer",
        start_date: "2020-01-01",
        end_date: "2022-12-31",
      },
      {
        id: 2,
        name_of_company: "Design Studio",
        role: "Graphic Designer",
        start_date: "2018-03-01",
        end_date: "2019-12-31",
      },
    ],
    employee_careers: [
      {
        id: 1,
        training_name: "Leadership Training",
        date: "2023-05-10",
        duration: "3 days",
        facilitator: "John Maxwell",
        venue: "Hilton Conference Center",
        document_name: "Leadership_Certificate.pdf",
        file: "https://example.com/certificates/Leadership_Certificate.pdf",
      },
      {
        id: 2,
        training_name: "Agile Development Workshop",
        date: "2022-11-15",
        duration: "5 days",
        facilitator: "Agile Academy",
        venue: "Tech Hub",
        document_name: null,
        file: null,
      },
    ],
    employee_academics: [
      {
        id: 1,
        school_name: "University of Technology",
        degree: "Bachelor's in Computer Science",
        graduation_date: "2019-06-20",
      },
      {
        id: 2,
        school_name: "State College",
        degree: "Diploma in Graphic Design",
        graduation_date: "2016-08-15",
      },
    ],
  };